### ISSUE TITLE
new action: JS script

### ISSUE THREAD

**Issue by RafaelGB** [RafaelGB/Obsidian-ZettelFlow#46]
Implementation of a pipeline concept where we can execute code with a defined I/O JSON

- [x] run JS correctly
- [x] js editor to construct scripts
- [x] Autocompletion functions
- [x] Refactor of note builder to create the note after the actions
- [x] Documentation

**Comment by RafaelGB** [comment]
![Image](https://github.com/RafaelGB/Obsidian-ZettelFlow/assets/11924043/00a1e0c7-2996-4a86-9ff8-207f9a028b65)
