### ISSUE TITLE
New node type: Script file

### ISSUE THREAD

**Issue by RafaelGB** [RafaelGB/Obsidian-ZettelFlow#47]
option to just DnD a JS file into the canvas and execute it

- [x] Include a config property with a path of js files as library
- [x] Editor for files (right click to modal or native editor view with a toggle option => another js editors compatible)
- [x] Add js files as node option on canvas
- [x] Cache per builder external libs
