### ISSUE TITLE
Add to exiting note

### ISSUE THREAD

**Issue by Suyashtnt** [RafaelGB/Obsidian-ZettelFlow#58]
I have a file I like to call "The quote book" which contains a bunch of quotes. Instead of creating a new file, I'd like the ability to append to this file, similar to how quickadd can do that. Basically I can create a note template and simply append said template into a file, rather than saving it to its own

**Comment by RafaelGB** [comment]
hello @Suyashtnt , That feature was in my roadmap but without an issue opened. Thanks for your suggestion!

I want to discuss about to configure another canvas to append info (with right click and with shortcut) to offer a better UX

**Comment by RafaelGB** [comment]
The editor workflow will have another canvas path

![Image](https://github.com/RafaelGB/Obsidian-ZettelFlow/assets/11924043/a6ac88b4-7c0f-4d5a-91ce-481d1e995cd3)


It will be used as context menu option:
![Image](https://github.com/RafaelGB/Obsidian-ZettelFlow/assets/11924043/d82cc06a-ff6f-4081-af7f-f213a7283080)


And it currently works, but some things should be improved:
- [ ] Remove custom options as target folder when you are editing the step inside the editors workflow
- [ ] Add a shortcut to trigger the Modal if the activeEditor is a MD. (In case the cursor is enabled, add the content to the cursor position but, in case it is disabled, will be added at the bottom of the note)
- [ ] Try to include the Zettelflow editor option inside the "insert" submenu
